foegelle@Forschungsrechner3-MaLSAMi:~/Masterarbeit/LaneNet2019/lanenet-lane-detection-master$ python3 tools/test_lanenet.py --is_batch False --batch_size 1 --save_dir data/testing/results --weights_path model/tusimple_lanenet/tusimple_lanenet_vgg_2019-05-01-19-39-30.ckpt-200000 --image_path data/testing/source_img/wheel84.png --use_gpu 1
I0516 11:36:21.233428 7943 test_lanenet.py:73] 开始读取图像数据并进行预处理
I0516 11:36:21.249862 7943 test_lanenet.py:79] 图像读取完毕, 耗时: 0.01630s
2019-05-16 11:36:23.435195: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-16 11:36:24.743268: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-05-16 11:36:24.743937: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: TITAN V major: 7 minor: 0 memoryClockRate(GHz): 1.455
pciBusID: 0000:42:00.0
totalMemory: 11.75GiB freeMemory: 11.34GiB
2019-05-16 11:36:24.841307: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 1 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:0a:00.0
totalMemory: 10.73GiB freeMemory: 10.53GiB
2019-05-16 11:36:24.841346: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0, 1
2019-05-16 11:36:25.315125: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-16 11:36:25.315164: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 1 
2019-05-16 11:36:25.315169: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N N 
2019-05-16 11:36:25.315172: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 1:   N N 
2019-05-16 11:36:25.315407: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9628 MB memory) -> physical GPU (device: 0, name: TITAN V, pci bus id: 0000:42:00.0, compute capability: 7.0)
INFO:tensorflow:Restoring parameters from model/tusimple_lanenet/tusimple_lanenet_vgg_2019-05-01-19-39-30.ckpt-200000
I0516 11:36:25.318751 7943 tf_logging.py:115] Restoring parameters from model/tusimple_lanenet/tusimple_lanenet_vgg_2019-05-01-19-39-30.ckpt-200000
2019-05-16 11:36:25.479898: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2019-05-16 11:36:25.479992: E tensorflow/stream_executor/cuda/cuda_dnn.cc:381] Possibly insufficient driver version: 410.104.0
2019-05-16 11:36:25.480010: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2019-05-16 11:36:25.480038: E tensorflow/stream_executor/cuda/cuda_dnn.cc:381] Possibly insufficient driver version: 410.104.0
Traceback (most recent call last):
  File "/home/foegelle/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/foegelle/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/foegelle/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node lanenet_model/inference/encode/conv1_1/conv/Conv2D}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](lanenet_model/inference/encode/conv1_1/conv/Conv2D-0-TransposeNHWCToNCHW-LayoutOptimizer, lanenet_model/inference/encode/conv1_1/conv/W/read)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test_lanenet.py", line 246, in <module>
    test_lanenet(args.image_path, args.weights_path, args.use_gpu)
  File "tools/test_lanenet.py", line 109, in test_lanenet
    feed_dict={input_tensor: [image]})
  File "/home/foegelle/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/foegelle/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/foegelle/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/foegelle/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node lanenet_model/inference/encode/conv1_1/conv/Conv2D (defined at /home/foegelle/Masterarbeit/LaneNet2019/lanenet-lane-detection-master/encoder_decoder_model/cnn_basenet.py:77)  = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](lanenet_model/inference/encode/conv1_1/conv/Conv2D-0-TransposeNHWCToNCHW-LayoutOptimizer, lanenet_model/inference/encode/conv1_1/conv/W/read)]]

Caused by op 'lanenet_model/inference/encode/conv1_1/conv/Conv2D', defined at:
  File "tools/test_lanenet.py", line 246, in <module>
    test_lanenet(args.image_path, args.weights_path, args.use_gpu)
  File "tools/test_lanenet.py", line 85, in test_lanenet
    binary_seg_ret, instance_seg_ret = net.inference(input_tensor=input_tensor, name='lanenet_model')
  File "/home/foegelle/Masterarbeit/LaneNet2019/lanenet-lane-detection-master/lanenet_model/lanenet_merge_model.py", line 156, in inference
    inference_ret = self._build_model(input_tensor=input_tensor, name='inference')
  File "/home/foegelle/Masterarbeit/LaneNet2019/lanenet-lane-detection-master/lanenet_model/lanenet_merge_model.py", line 67, in _build_model
    name='encode')
  File "/home/foegelle/Masterarbeit/LaneNet2019/lanenet-lane-detection-master/encoder_decoder_model/vgg_encoder.py", line 95, in encode
    out_dims=64, name='conv1_1')
  File "/home/foegelle/Masterarbeit/LaneNet2019/lanenet-lane-detection-master/encoder_decoder_model/vgg_encoder.py", line 55, in _conv_stage
    use_bias=False, padding=pad, name='conv')
  File "/home/foegelle/Masterarbeit/LaneNet2019/lanenet-lane-detection-master/encoder_decoder_model/cnn_basenet.py", line 77, in conv2d
    conv = tf.nn.conv2d(inputdata, w, strides, padding, data_format=data_format)
  File "/home/foegelle/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 957, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/home/foegelle/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/foegelle/.local/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/foegelle/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/foegelle/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node lanenet_model/inference/encode/conv1_1/conv/Conv2D (defined at /home/foegelle/Masterarbeit/LaneNet2019/lanenet-lane-detection-master/encoder_decoder_model/cnn_basenet.py:77)  = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](lanenet_model/inference/encode/conv1_1/conv/Conv2D-0-TransposeNHWCToNCHW-LayoutOptimizer, lanenet_model/inference/encode/conv1_1/conv/W/read)]]

